"""Constants relevant to SBS data processing."""

# Constants
PREFIX = "prefix"
SGRNA = "sgRNA"
GENE_SYMBOL = "gene_symbol"
GENE_ID = "gene_id"
WELL = "well"
TILE = "tile"
CELL = "cell"
READ = "read"
BARCODE = "barcode"
BARCODE_COUNT = "barcode_count"
BARCODE_0 = "cell_barcode_0"
BARCODE_1 = "cell_barcode_1"
BARCODE_COUNT_0 = "cell_barcode_count_0"
BARCODE_COUNT_1 = "cell_barcode_count_1"
UMI = "UMI"
UMI_COUNT = "UMI_count"
UMI_0 = "cell_UMI_0"
UMI_1 = "cell_UMI_1"
UMI_COUNT_0 = "cell_UMI_count_0"
UMI_COUNT_1 = "cell_UMI_count_1"
POSITION_I = "i"
POSITION_J = "j"
CHANNEL = "channel"
CYCLE = "cycle"
INTENSITY = "intensity"
